ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
  path: /grafana/?(.*)
  hosts:
    - mytutorlocal.app
grafana.ini:
  server:
    root_url: http://localhost/grafana # this host can be localhost